ABCD_data <- readRDS("nda2.0.1.Rds")  #reading in ABCD 2.0.1 data

myvars <- c("subjectid",              #making a list of wanted variables
            "eventname",
            "interview_age",
            "sex",
            "race_ethnicity",
            "anthro_height_calc",
            "anthro_weight_calc",
            "anthro_waist_cm",
            "screentime_1_hours_p",
            "screentime_1_minutes_p",
            "screentime_2_hours_p",
            "screentime_2_minutes_p",
            "physical_activity_1",
            "ksads_4_826_t",
            "ksads_4_828_t",
            "ksads_2_830_t",
            "ksads_2_831_t",
            "ksads_2_832_t",
            "ksads_2_835_t",
            "ksads_2_836_t",
            "ksads_2_838_t",
            "ksads_1_840_t",
            "ksads_1_843_t",
            "ksads_1_846_t",
            "ksads_4_851_t",
            "ksads_14_853_t",
            "ksads_5_857_t",
            "ksads_6_859_t",
            "ksads_7_861_t",
            "ksads_8_863_t",
            "ksads_9_867_t",
            "ksads_10_869_t",
            "ksads_20_889_t",
            "ksads_11_917_t",
            "ksads_21_921_t",
            "ksads_13_929_t",
            "ksads_13_932_t",
            "ksads_13_935_t",
            "ksads_13_938_t",
            "ksads_23_945_t",
            "ksads_23_946_t",
            "ksads_23_947_t",
            "ksads_23_948_t",
            "ksads_23_949_t",
            "ksads_23_950_t",
            "ksads_23_954_t",
            "upps_y_ss_negative_urgency",
            "upps_y_ss_lack_of_planning",
            "upps_y_ss_sensation_seeking",
            "upps_y_ss_positive_urgency",
            "bisbas_ss_bis_sum",
            "bisbas_ss_bas_rr",
            "bisbas_ss_bas_drive",
            "bisbas_ss_bas_fs",
            "bisbas_ss_bism_sum",
            "bisbas_ss_basm_rr",
            "bisbas_ss_basm_drive",
            "cbcl_scr_syn_anxdep_r",
            "cbcl_scr_syn_withdep_r",
            "cbcl_scr_syn_somatic_r",
            "cbcl_scr_syn_social_r",
            "cbcl_scr_syn_thought_r",
            "cbcl_scr_syn_attention_r",
            "cbcl_scr_syn_rulebreak_r",
            "cbcl_scr_syn_aggressive_r",
            "cbcl_scr_syn_internal_r",
            "cbcl_scr_syn_external_r",
            "cbcl_scr_syn_totprob_r",
            "cbcl_scr_dsm5_depress_r",
            "cbcl_scr_dsm5_anxdisord_r",
            "cbcl_scr_dsm5_somaticpr_r",
            "cbcl_scr_dsm5_adhd_r",
            "cbcl_scr_dsm5_opposit_r",
            "cbcl_scr_dsm5_conduct_r",
            "cbcl_scr_07_sct_r",
            "cbcl_scr_07_ocd_r",
            "cbcl_scr_07_stress_r",
            "su_tlfb_alc_sip",
            "su_tlfb_alc_use",
            "su_tlfb_tob_puff",
            "su_tlfb_cig_use",
            "su_tlfb_ecig_use",
            "su_tlfb_mj_puff",
            "su_tlfb_mj_use",
            "su_tlfb_coc_use",
            "su_tlfb_meth_use",
            "su_tlfb_mdma_use",
            "su_tlfb_ket_use",
            
            
            
            

 
            "demo_comb_income_p_l",
            "demo_prnt_ed_p_l",
            "demo_prtnr_ed_p_l",
            "demo_prnt_empl_p_l",
            "demo_prtnr_empl_p_l",
            "demo_prnt_prtnr_l",
            "demo_roster_p_l",
            "demo_fam_exp1_p_l",
            "demo_fam_exp2_p_l",
            "demo_fam_exp3_p_l",
            "demo_fam_exp4_p_l",
            "demo_fam_exp5_p_l",
            "demo_fam_exp6_p_l",
            "demo_fam_exp7_p_l")


subsetABCDdata <- ABCD_data[myvars]   #subsetting wanted variables from the complete ABCD 2.0.1 dataset
write.csv(subsetABCDdata, file = "subsetABCDdata.csv")  #csv output of table with specified variables